name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, integration ]

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Create temporary directories
        run: mkdir -p build output
      - name: Compile test runner
        run: clang -Werror -g -lm ufbx_write.c test/runner.c test/ufbx.c -o build/test-runner
      - name: Run tests
        run: build/test-runner
